version: '3.8'
services:
  # nginx
  afr-nginx:
    container_name: afr-nginx
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www/afr
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - afr-php
      - afr-mariadb
    networks:
      - afr

  #php
  afr-php:
    container_name: afr-php
    build:
      context: .
      dockerfile: ./_docker/php/php.dockerfile
    volumes:
      - ./src/:/var/www/afr
      - ./_docker/php/php.ini:/usr/local/etc/php/php.ini
    command: php-fpm

    depends_on:
      - afr-mariadb
    ports:
      - "5004:5004"
    networks:
      - afr

  #mariadb
  afr-mariadb:
    container_name: afr-mariadb
    image: mariadb:latest
    ports:
      - "5003:3306"
    volumes:
      - ./_docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: apprendrefr
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - afr

  afr-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - afr-mariadb:db
    restart: always
    ports:
      - "5002:80"
    environment:
      UPLOAD_LIMIT: 500M
      PMA_ARBITRARY: 1
    networks:
      - afr

networks:
  afr:
